version: '3.4'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres:3.3.2"
    container_name: "mytb"
    ports:
      - "9090:9090"
      - "1884:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    healthcheck:
      # test command is executed inside container -> use internal TB port
      test: curl http://localhost:9090 || exit 1
      interval: 20s
      start_period: 120s
      timeout: 5s
      retries: 3
